sudo: false
dist: bionic

language: cpp
compiler:
  - clang
 
git:
  depth: 1

services:
  - mysql

addons:
  apt:
    update: true
    sources:
    packages:
      - libssl-dev
      - libmysqlclient-dev
      - libreadline-dev
      - zlib1g-dev
      - libbz2-dev
      - libboost-dev
      - libboost-thread-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-iostreams-dev
      # For data archive
      - p7zip

before_install:
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init
 
install:
  - mysql -uroot -e 'create database test_mysql'
  - mkdir bin logs data
  - cd bin
  - cmake ../ -DPLAYERBOT=1 -DTOOLS=1 -DSCRIPTS=dynamic -DTESTS=1 -DCMAKE_BUILD_TYPE=Debug -DWITH_COREDEBUG=1 -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - $CXX --version
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -utrinity -ptrinity auth < sql/base/auth_database.sql
  - ./contrib/check_updates.sh auth auth localhost
  - mysql -utrinity -ptrinity characters < sql/base/characters_database.sql
  - ./contrib/check_updates.sh characters characters localhost
  - mysql -utrinity -ptrinity logs < sql/base/logs_database.sql
  - ./contrib/check_updates.sh logs logs localhost
  - mysql -utrinity -ptrinity world < sql/base/dev/world_database.sql
  - cat sql/updates/world/*.sql | mysql -utrinity -ptrinity world
  - mysql -uroot < sql/create/drop_mysql.sql
  - cd bin
  - make -j 4 -k && make install
  - cd check_install
  - ls
  - cd bin
  - ./authserver --version
  - ./worldserver --version
